version: 18.2.16.{build}
image: Visual Studio 2017
test: off

configuration:
- Release
- Debug

matrix:
  fast_finish: true

install:
  - git submodule update --init --recursive

before_build:
- cmd: >-
    mkdir build

    cd build

    cmake --version

    cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_PREFIX_PATH=C:\Qt\5.10.1\msvc2017_64

build:
  project: c:\projects\spaghetti\build\Spaghetti.sln
  verbosity: minimal
  parallel: true


after_build:
- cmd: >-
    cd build
    
    dir C:\Qt\5.10.1
    
    set PATH=%PATH%;C:\Qt\5.10.1\bin

    windeployqt --version

    windeployqt build\bin\Release

artifacts:
  - path: build
    name: Spaghetti
    type: zip
